module.exports = {
  getPhrase: function() {
    phrases = [
      "Que te repites más que un capítulo de los Power Rangers. ",
      "Tienes que tener mas cuidado que el Capitán Garfio en un picor de huevos. ",
      "Eres más pesado que la pelota cayendo de Oliver y Benji. ",
      "Que eres más largo que la serie Sensación de Vivirl, que nunca se acaba. ",
      "Te lías más que los chicos de Sensación de Vivirl. ",
      "Tiene má peligro que Krispín en la cola de agacharse para hacer el potro. ",
      "Que trabaja menorrl que Antonio Davírrl Flores. ",
      "Tienes mas peligro que Pinocho haciendo el 69. ",
      "Tiene mas peligro que Masiel en una barra libre. ",
      "Pierdes mas el tiempo que Letisia Sabaterl debajo de una lámpara de rayos uva. ",
      "Lo pasas más mal que la Reme haciendo Showgirls. ",
      "Tienes mas peligro que Freddy Krugerrl cuando se la han olvidado los donuts. ",
      "Tiene mas morro que un pintor de arte abstracto. ",
      "Te vas mas de los programarrl que el Padre Apeles. ",
      "Fastidias mas que Bigote Arrocet en la película de Chiquito de la Calzada. ",
      "Tienes mas peligro que Pamela Anderson haciendo el canguro sin sujetador. ",
      "Eres mas falso que Belinda y Chapis anunciando el Apiserum y el champú en el QMDrrs. ",
      "Eres mas falso que el bronceado de Letisia Sabaterrl. ",
      "Das mas sombra que Rosy de Palma delante del sol. ",
      "Que eres má pesao que una vaca en brazorrrrssslllll. Hijo miorll!!! ",
      "Que estás más incómodo que Jack el Destripador en una comuna Hippy. ¡Qué lo sepass! ",
      "Vas más lento que el PC de Pedro Picapiedra. ",
      "Pol la gloria de mi madre que eres más feo que Protsinesky chupando un limón. ",
      "Pol la gloria de mi madre que eres más feo quel sobacor de una cucaracharrl. ",
      "Eres más peligroso que abrir un paquete de tabaco delante de un aparcacoches. ",
      "Fallas más que el Stevie Wonder sessuarrrr tirando al plato… ",
      "Tiene má aguanterrr que el estómago de Pepe Navarrorl! ",
      "Hija mía, que te explicas menos que José Manuel Lara imitando a Rambo, jaaarl… ",
      "Que trabajas menoss que el ángel de la guarda de los Kennedyrrrlll Pecadores!!! ",
      "Tienes menos imaginación que el chefffff de McDonald’s!! ",
      "Tienes más peligro que un mono con un hacha. ",
      "Jarrrl, que eres más feo que la foto de un pedo…. ",
      "Eres más pesado que el cuñado del Roky. ",
      "Francamente querida, a mí eso me preocupa menos que la final de petanca individual ",
      "femenina de Malabo, jarl… ",
      "Esto está más fresquito que el frigorífico de NANUC el esquimalrr. ",
      "Tienes más peligro que el modoso en un vestuario de la selección española deWaterpolo. ",
      "Eres más feo que robar a Caritas. ",
      "Ponme rápido una copa fistro, que estoy más seco que el Barco de Chanqueteeerl. ",
      "Estás más afixciao que Dar Veider en una caja de cristaaaarrrll!! ",
      "Tienes más vidaaaar, jor, que los caballeros del zodiacor. ",
      "Que tienes menos futuro qu’una gota d’agua en pleno desierto. ",
      "¡Que tienes más tonteridas que el neceser de la abuela de McGuiver! ",
      "Que estás más tenso que Rodolfo Langostinorl en un cóckterl… ",
      "Que eres más lento que Internet en vacaciones. ",
      "Eres más SORPRENDENTEERRR que la Gemio en un roscón de reyes. ",
      "¡Tienes más marcha que el carro de la doctora Queen! ",
      "Estás más desgastado que las ruedas del Coche Fantástico. ",
      "Te ves menos que el murciélago del escudo del Valencia ",
      "Trabajas menos que el forense del Equipo-A. ",
      "Eres más peligroso que una caja de bombas. ",
      "Estás más perdido que el tio del anuncio de Martini cuando se quita las gafas. ",
      "Tienesss menos futuror… que la Reme en el ballet del Semáforor. ",
      "Tienes más peligro que un Gremlin comulgando en la Misa del Gallo. ",
      "Que eres más pequeño que el walkman de Davirr el gnomor. ",
      "¡Gastas menos que un Japonés en boinas, ¡¡¡TACAÑORJALLLL!!! ",
      "Estás más perdido que Wally en el Frente Atlético. ",
      "Tienes más peligro que Zubi a la salida de un córner. ",
      "Tú, eres más hortera que un ratón con pegatinas. ",
      "Eres más presumida que una perdiz con ligas. ",
      "Tengo el piso más desordenado que el dormitorio de un pavo. ",
      "Que estás más buscado que la grabación del chiste de la vaca contado por Curro. ",
      "Que tienes menos reflejos, que un espejorrr de corchorr. ",
      "Que tienes más cabeza que un puesto de muñequitorrr. ",
      "Hijo mío eres más impresentable que la tarjeta de visita de Luis Roldán. ",
      "Y además lo tienes más crudo que el auditor de cuentas de las empresas de Javier de la Rosa. ",
      "Que estás más 'picao' que el bonobus de Willy Fog. ",
      "Eres más falso que lucas Grijander disfrazado de argamboy. ",
      "Por la gloria de mi madre, que trabajas menos que el locutor del hilo musicarlll. ",
      "Que eres más lento de cargar que el gueb del caballo del malorr. ",
      "Que estás más concurrío que el gueb de la Apamela Jandersonsonson. ",
      "Hija mía, eres más culé que la bambina de Catalana Occidente, jarll. ",
      "Trabajas menos que el ballet de Informe Semanal, que lo sepasss… ",
      "Por la gloria de mi madre, que eres más pesado que el neceser de Claudia Schiffer… ",
      "Hijo mío, que tienes menos gracia que Sonsoles Suárez presentando el Sorpresa Sorpresa… ",
      "Hijo mío aciertas más que una quiniela de quince triples. ",
      "Que tienes la cabeza más grande que si te la pintas de verde parece un contenedor de Vídreo. ",
      "Eres más pesado que el bote de 3 en 1 de Mazinger Z… ",
      "¡Que lo sepasss! Eres más inofensivo que las balas del equipo A. ",
      "Eres más peligroso que Mcgyber con un chicle boomer y un palillo. ",
      "Que eres más pelota que el Ambrosio con los Ferrero Rocherrrr…jarrr cobarde. ",
      "Que eres más vaga que la jefa de Ambrosio. ",
      "Meneas más la cabeza que la del anuncio del Panten pro-V. ",
      "Estás más ilusionado que el jorobadorl de Notre Dame en la corporación dermoestética… ¡jarl! ",
      "Estás más perdido que un submarinista en un desierto, ¿comoorrrrr? ",
      "Que eres más infantil que un bocata de gominolas, ¡¡cobarderr!! ",
      "Eres más inútil que un equipo de música turbo-jander en el Club de los Sordos, que lo sepas…! ",
      "Por la gloria de mi madre, que haces menos galas que el cantante mudo… ",
      "Jaaarrrll trabajas menos que el escritor analfabeto. ",
      "Tienes más peligro que Atila después de ver los Power Rangers… jarl, que te hace un hamatoma… ",
      "Que tienes más problemas que Robocop pasando por el detector de metales… que lo sepasss… ",
      "Tienes menos paciencia que la novia del zagal de Villaabajo, ¡torpedo! ",
      "Estás más perdío que una neuronaar en una película de Ramboooor!!!!! ",
      "Noorrr. Tienes menos carne que la barriga de la Griffit después de la liposucciorrrr. ",
      "Que te comes menos que Camilo VI con un tanga de leopardo por Chipiona. ",
      "Estás más confiado que Petete en la Universidad. ",
      "Andas más despistado que Carmen Sevilla en Barrio Sésamo. ",
      "Tienes peor carácter que Stoichov en ayunas. ",
      "Tengo menos dinero que el que se está bañando. ",
      "Date cuen que tienes menos futuro quel manco de Lepanto tocando el pianooooorrrrl. ",
      "Tienes menos futuro que Llongueras en el Tibet. ",
      "Tienes menos luces que la linterna de David el NOMO. ",
      "Que váis más 'apretaos' que traje de luces. ",
      "Que tienes la nariz más grande que la de Rossy de Palma, que cuando estornuda, hay tres días de niebla en 'to' Madrid, que lo sepas. ",
      "También, janders, cuando hace el muerto en el mar, parace que hay tiburoners, y esta tía ",
      "es capaz de ducharse fumando un cigarro, porque no se le apaga. ",
      "Te ríes más que la vaca en porciones extras. ",
      "Eres más peligroso que Julio Iglesias empachado de Casera. ",
      "Janderrl! Pekador, que eres más feo que el Ronaldo cuando se lesiona. ",
      "Qué estáis más repetidos que las sonrisas de las chicas del Telecupón… ",
      "Tienes menos futuro que una tertulia entre Chabeli janderiglesias y su hermano Enriquito el torpedito. ",
    ];

    return phrases[Math.floor(Math.random()*phrases.length)];
  },
  getJoke: function() {
    videos = [
      'Cvhvw0mBWus',
      'bk5uIOvfD3A',
      'jDonMMtclPQ',
      'rgKZs1yIHMI',
      'ndLk1hQkeOI',
      'a3iYGPBMJcg',
      'cUmnMi_TP9Q',
      'E7EuqFmycis',
      'Ok6q8ZmsHyc',
      '1REwHGEN84k'
    ];

    video = videos[Math.floor(Math.random()*videos.length)];

    return '<iframe width="320" height="180" src="https://www.youtube.com/embed/'+video+'" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>';

  }
};
